### ISSUE TITLE
如何修改代码导出excel呀？

### ISSUE THREAD

**Issue by fengshaokun** [AngelLiang/wos-download-bot#1]

**Comment by AngelLiang** [comment]
在`genRequestData`函数中可以查看请求参数哈，目前参数是写死的，如下：

```
{
            "parentQid": getParentQid(),
            "sortBy": "relevance",
            "displayTimesCited": "true",
            "displayCitedRefs": "true",
            "product": "UA",
            "colName": "WOS",
            "displayUsageInfo": "true",
            "fileOpt": "othersoftware",
            "action": "saveToFieldTagged",
            "markFrom": start,
            "markTo": stop,
            "view": "summary",
            "isRefQuery": "false",
            "locale": "en_US",
            "filters": "fullRecordPlus",
            "bm-telemetry": get_bm_telemetry()
        }
```

我去查了一下excel下载的请求参数，下载excel请求参数如下：

```
{
  "parentQid": "...",
  "sortBy": "relevance",
  "displayTimesCited": "true",
  "displayCitedRefs": "true",
  "product": "UA",
  "colName": "WOS",
  "displayUsageInfo": "true",
  "fileOpt": "xls",
  "action": "saveToExcel",
  "markFrom": "...",
  "markTo": "...",
  "view": "summary",
  "isRefQuery": "false",
  "locale": "zh_CN",
  "filters": "authorTitleSource",
  "bm-telemetry": "..."
}
```

所以你可以试试把以下key改一下：

- "fileOpt": "xls"
- "action": "saveToExcel",

**Comment by tsingyu42** [comment]
同理，希望能增加 ris 的选项，目前最新版 Zotero 已经不支持 txt 了

**Comment by tsingyu42** [comment]
<img width="855" alt="image" src="https://github.com/AngelLiang/wos-download-bot/assets/40352237/2e77bd4a-9ea2-471d-b599-e5b2796608e7">

RIS 的话除了文件后缀参数，就是把 `action` 的值改成 `exportToRis` ?

---

噢不对，不是这个

**Comment by tsingyu42** [comment]
> <img alt="image" width="855" src="https://user-images.githubusercontent.com/40352237/253180079-2e77bd4a-9ea2-471d-b599-e5b2796608e7.png">
> RIS 的话除了文件后缀参数，就是把 `action` 的值改成 `exportToRis` ?
> 
> 噢不对，不是这个

已解决，虽然还不够优雅（额外创建一个脚本，而非在单个脚本里实现各种选项同时出现）：https://gist.github.com/karanotsingyu/edd4b00a7bbff47d0b317ea8b4eb16e1
