### ISSUE TITLE
报错信息如图，如何确定具体发生了什么问题

### ISSUE THREAD

**Issue by tsingyu42** [AngelLiang/wos-download-bot#2]
<img width="448" alt="image" src="https://github.com/AngelLiang/wos-download-bot/assets/40352237/3aaef312-4f99-441b-bf10-e4c7305011a5">

* Chrome Version 114.0.5735.133 (Official Build) (arm64)
* Tamper Monkey v4.18.1

**Comment by AngelLiang** [comment]
估计是wos那边改版，需要调整代码

**Comment by AngelLiang** [comment]
v1.3.1版本已经修复
